### ISSUE TITLE
Broken??

### ISSUE THREAD

**Issue by DatOnePlayer** [AzhurniyBaklan/Metaglaphite#1]
I can't find them in game, although I downloaded it and put it on the mods file

**Comment by AzhurniyBaklan** [comment]
> I can't find them in game, although I downloaded it and put it on the mods file
@DatOnePlayer When you download this mod from "Release" you get .zip file. Extract this file anywhere you want, then you'll get "Metaglaphite v1.xx" folder. This folder contains "metaglaphite" mod folder. You need to place in your mods only this folder, nothing else.

**Comment by DatOnePlayer** [comment]
I downloaded this one only

**Comment by DatOnePlayer** [comment]
I don't know there's a release ones
@AzhurniyBaklan

**Comment by DatOnePlayer** [comment]
Hello??

**Comment by AzhurniyBaklan** [comment]
> I don't know there's a release ones
> @AzhurniyBaklan



> Hello??

Hi, I've made a video-guide just about downloading. https://youtu.be/Qm5PUdZ4A7Y
Feel free to ask if you didn't understand anything.

**Comment by DatOnePlayer** [comment]
I only saw you move the files out and didn't move them to mindustry files, help please?
@AzhurniyBaklan

**Comment by AzhurniyBaklan** [comment]
> I only saw you move the files out and didn't move them to mindustry files, help please?
> @AzhurniyBaklan
I thought it was pretty obvious, but okay then, guide number 2 https://youtu.be/08P53WhhY3E
